# Generated by Django 3.2.12 on 2022-03-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=200)),
                ('MRP', models.CharField(max_length=200)),
                ('Discount_price', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='products')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaapp.category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melaapp.sellregister')),
            ],
        ),
    ]
