# Generated by Django 3.2.12 on 2022-03-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='productt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('Warranty', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='products')),
                ('Specification', models.CharField(max_length=200)),
                ('purchased_year', models.IntegerField(max_length=10)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaapp.category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melaapp.sellregister')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
