# Generated by Django 3.2.12 on 2022-03-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0005_alter_productt_purchased_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productt',
            name='Warranty',
        ),
    ]
