# Generated by Django 3.2.12 on 2022-03-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0006_remove_productt_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productt',
            name='Specification',
            field=models.TextField(),
        ),
    ]
