# Generated by Django 3.2.12 on 2022-03-20 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0007_alter_productt_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('card_number', models.IntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('payment_status', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melaapp.customeregister')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaapp.productt')),
            ],
        ),
    ]
