# Generated by Django 3.2.12 on 2022-03-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0009_alter_customerrequest_cvv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRequest',
        ),
    ]
