# Generated by Django 3.2.12 on 2022-03-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0012_auto_20220320_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='amount',
        ),
    ]
