# Generated by Django 3.2.12 on 2022-03-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0013_remove_customerrequest_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='seller',
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaapp.productt'),
        ),
    ]
