# Generated by Django 3.2.12 on 2022-03-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0014_auto_20220320_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melaapp.customeregister')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melaapp.sellregister')),
            ],
        ),
    ]
