# Generated by Django 3.2.12 on 2022-03-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melaapp', '0015_cfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfeedback',
            name='seller',
        ),
    ]
